#!/usr/bin/env python3
"""
Scan task/archive for numbered tasks; diff against task/knowledge/refresh-manifest.yaml.

Lives under iom-todo-task-knowledge skill — not repo-root scripts/.

Usage (from workspace root):
  python .agents/skills/iom-todo-task-knowledge/scripts/knowledge-manifest.py
  python .agents/skills/iom-todo-task-knowledge/scripts/knowledge-manifest.py --write
  python .agents/skills/iom-todo-task-knowledge/scripts/knowledge-manifest.py --init
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from datetime import date
from pathlib import Path

# skill/scripts → skill → skills → .agents → repo root
ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent
ARCHIVE = ROOT / "task" / "archive"
MANIFEST_PATH = ROOT / "task" / "knowledge" / "refresh-manifest.yaml"

NUMBERED = re.compile(r"^[0-9]{3,}-.*\.md$")
HANDOFF = re.compile(r"\.handoff", re.I)
SLUG_LINE = re.compile(r"^  ([0-9]{3,}-[^:]+):$")
FM_KEY = re.compile(r"^[a-z_]+$")


def parse_frontmatter(text: str) -> dict[str, str]:
    m = re.match(r"^---\r?\n([\s\S]*?)\r?\n---", text)
    if not m:
        return {}
    out: dict[str, str] = {}
    for line in m.group(1).splitlines():
        idx = line.find(":")
        if idx <= 0:
            continue
        key = line[:idx].strip()
        if not FM_KEY.match(key):
            continue
        val = line[idx + 1 :].strip()
        if (val.startswith('"') and val.endswith('"')) or (
            val.startswith("'") and val.endswith("'")
        ):
            val = val[1:-1]
        out[key] = val
    return out


def walk_archive(directory: Path) -> list[dict]:
    acc: list[dict] = []
    if not directory.is_dir():
        return acc
    for full in directory.rglob("*.md"):
        name = full.name
        if not NUMBERED.match(name) or HANDOFF.search(name):
            continue
        raw = full.read_bytes()
        text = raw.decode("utf-8")
        fm = parse_frontmatter(text)
        slug = name[:-3]
        rel = full.relative_to(ROOT).as_posix()
        acc.append(
            {
                "slug": slug,
                "path": rel,
                "content_hash": hashlib.sha256(raw).hexdigest()[:16],
                "type": fm.get("type", ""),
                "created": fm.get("created", ""),
                "updated": fm.get("updated", ""),
            }
        )
    acc.sort(key=lambda t: t["slug"])
    return acc


def parse_simple_yaml(text: str) -> dict:
    manifest: dict = {"version": 1, "last_full_refresh": None, "tasks": {}}
    current_slug: str | None = None
    for line in text.splitlines():
        if line.startswith("version:"):
            try:
                manifest["version"] = int(line.split(":", 1)[1].strip()) or 1
            except ValueError:
                manifest["version"] = 1
        if line.startswith("last_full_refresh:"):
            v = line.split(":", 1)[1].strip()
            manifest["last_full_refresh"] = (
                None if v in ("null", "") else v.strip('"').strip("'")
            )
        slug_match = SLUG_LINE.match(line)
        if slug_match:
            current_slug = slug_match.group(1)
            manifest["tasks"][current_slug] = {}
            continue
        if current_slug and line.startswith("    "):
            kv = line.strip().split(":", 1)
            if len(kv) != 2:
                continue
            key, val = kv[0], kv[1].strip()
            if val in ("null", ""):
                manifest["tasks"][current_slug][key] = None
            else:
                manifest["tasks"][current_slug][key] = val.strip('"').strip("'")
    return manifest


def serialize_manifest(manifest: dict) -> str:
    lines = [
        "# Generated by iom-todo-task-knowledge/scripts/knowledge-manifest.py",
        f"version: {manifest.get('version', 1)}",
        f"last_full_refresh: {json.dumps(manifest.get('last_full_refresh')) if manifest.get('last_full_refresh') else 'null'}",
        "tasks:",
    ]
    slugs = sorted(manifest.get("tasks", {}).keys())
    if not slugs:
        lines.append("  {}")
    for slug in slugs:
        t = manifest["tasks"][slug]
        lines.append(f"  {slug}:")
        for k in ("path", "content_hash", "type", "created", "updated", "ingested_at"):
            v = t.get(k)
            if v is None:
                lines.append(f"    {k}: null")
            else:
                lines.append(f'    {k}: "{v}"')
    return "\n".join(lines) + "\n"


def diff(archive_tasks: list[dict], manifest: dict) -> dict:
    known = manifest.get("tasks") or {}
    archive_by_slug = {t["slug"]: t for t in archive_tasks}
    new_slugs = [t["slug"] for t in archive_tasks if t["slug"] not in known]
    changed = [
        t["slug"]
        for t in archive_tasks
        if t["slug"] in known and known[t["slug"]].get("content_hash") != t["content_hash"]
    ]
    skipped = [
        t["slug"]
        for t in archive_tasks
        if t["slug"] in known and known[t["slug"]].get("content_hash") == t["content_hash"]
    ]
    removed = [s for s in known if s not in archive_by_slug]
    return {
        "newSlugs": new_slugs,
        "changed": changed,
        "skipped": skipped,
        "removed": removed,
        "archiveTasks": archive_tasks,
        "total": len(archive_tasks),
    }


def main() -> None:
    write = "--write" in sys.argv
    init = "--init" in sys.argv
    today = date.today().isoformat()

    archive_tasks = walk_archive(ARCHIVE)
    manifest: dict = {"version": 1, "last_full_refresh": None, "tasks": {}}
    if MANIFEST_PATH.is_file():
        manifest = parse_simple_yaml(MANIFEST_PATH.read_text(encoding="utf-8"))

    result = diff(archive_tasks, manifest)

    if write or init:
        next_manifest = {
            "version": 1,
            "last_full_refresh": manifest.get("last_full_refresh"),
            "tasks": dict(manifest.get("tasks") or {}),
        }
        to_ingest = (
            [t["slug"] for t in archive_tasks]
            if init
            else result["newSlugs"] + result["changed"]
        )

        if init:
            next_manifest["last_full_refresh"] = today

        for slug in result["removed"]:
            next_manifest["tasks"].pop(slug, None)

        for t in archive_tasks:
            slug = t["slug"]
            if init or slug in to_ingest:
                prev = (manifest.get("tasks") or {}).get(slug, {})
                ingested_at = (
                    today
                    if init or not prev
                    else prev.get("ingested_at") or today
                )
                if slug in result["changed"]:
                    ingested_at = today
                next_manifest["tasks"][slug] = {
                    "path": t["path"],
                    "content_hash": t["content_hash"],
                    "type": t["type"],
                    "created": t["created"],
                    "updated": t["updated"],
                    "ingested_at": ingested_at,
                }
            elif slug in next_manifest["tasks"]:
                next_manifest["tasks"][slug]["path"] = t["path"]
                next_manifest["tasks"][slug]["type"] = t["type"]
                next_manifest["tasks"][slug]["created"] = t["created"]
                next_manifest["tasks"][slug]["updated"] = t["updated"]

        MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
        MANIFEST_PATH.write_text(serialize_manifest(next_manifest), encoding="utf-8")
        out = {**result, "wrote": str(MANIFEST_PATH), "mode": "init" if init else "write"}
        print(json.dumps(out, indent=2))
        return

    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
